### PR TITLE
2nd Level "C" Spells

### PR DESCRIPTION
**Pull request by ChrisSpangler**
2nd Level "C" Spells Complete for Review

### CODE REVIEW

**Review by magicalmusings — CHANGES_REQUESTED** [review]
They all look perfect @ChrisSpangler! Only thing I would ask is to move the spells from the 
```_posts/spells/cantrips/``` folder to the ```_posts/spells/second-level/``` in the repo. Thanks!

**Comment by ChrisSpangler** [comment]
Done! Moved into the 2nd lvl folder

**Review by magicalmusings — CHANGES_REQUESTED** [review]
Good for merge! Thank you so much for your help

**Review by magicalmusings — APPROVED** [review]
Sorry, hit the wrong button there

**Pull request merged**
