### PR TITLE
Added remaining 8 level spells

### PR DESCRIPTION
**Pull request by gremlin97**
This contributes to #28

### CODE REVIEW

**Review by magicalmusings — CHANGES_REQUESTED** [review]
Content is fantastic, just please double check the sources for each spell. Abi-Dalzim's Horrid WIlting, for example, is in the "Elemental Evil Player's Companion". 

Once that's fixed it's good for approval and merge!

**Comment by gremlin97** [comment]
Thank you :smile:  Working on it!

**Review by magicalmusings — APPROVED** [review]

**Comment by magicalmusings** [comment]
PR looks great, thank you for your help @gremlin97

**Comment by gremlin97** [comment]
Welcome! Looking forward to contribute more :smile:

**Pull request merged**
